# Site settings
title: TimeLayers
url: timelayers.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

authors:
  - name: Aylin B. Yildirim Tschoepe
    title: Chief Academic Officer
    email: aylin.yt@gmail.com
    link: Aylin
  - name: Luis Alberto Barradas Chacón
    title: Chief Information Officer
    email: abcsds@gmail.com
    link: Alberto
  - name: Dominic Tschoepe
    title: Chief Creative Officer
    email: dominic.tschoepe@gmail.com
    link: Dominic


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-gray: '#333333'
  links: '#FFD133'

# Footer settings
footer: TimeLabs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/abcsds
  - title: facebook
    url: https://facebook.com
  - title: github
    url: https://github.com/abcsds

# Build settings
markdown: kramdown
permalink: pretty
